If we have gmake, use GNUmakefile and do not overwrite Makefile. Closes #805. This also adds a missing @SET_MAKE@ that was likely intended to be included in every makefile since we've been using AC_PROG_MAKE_SET for long.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -624,7 +624,8 @@ ac_includes_default="\
 #endif"
 
 ac_header_list=
-ac_subst_vars='LTLIBOBJS
+ac_subst_vars='HAVE_GIT
+LTLIBOBJS
 HOST_OS
 PLUGFORMATS_OBJS
 EXE_EXT
@@ -679,6 +680,7 @@ SORT
 MKDIR_P
 CPP
 SET_MAKE
+ifGNUmake
 SED
 GREP
 LN_S
@@ -705,7 +707,6 @@ LD
 AS
 YASM
 CFLAGS_EXTRA
-HAVE_GIT
 target_alias
 host_alias
 build_alias
@@ -3296,6 +3297,66 @@ ac_config_headers="$ac_config_headers autoconfig.h"
 # generic macros. Rather than hack ax_opencl.m4 we include this here (the
 # original has been obsoleted by AX_COMPILER_VENDOR or something like that)
 
+# ===========================================================================
+#     http://www.gnu.org/software/autoconf-archive/ax_check_gnu_make.html
+# ===========================================================================
+#
+# SYNOPSIS
+#
+#   AX_CHECK_GNU_MAKE()
+#
+# DESCRIPTION
+#
+#   This macro searches for a GNU version of make. If a match is found, the
+#   makefile variable `ifGNUmake' is set to the empty string, otherwise it
+#   is set to "#". This is useful for including a special features in a
+#   Makefile, which cannot be handled by other versions of make. The
+#   variable _cv_gnu_make_command is set to the command to invoke GNU make
+#   if it exists, the empty string otherwise.
+#
+#   Here is an example of its use:
+#
+#   Makefile.in might contain:
+#
+#     # A failsafe way of putting a dependency rule into a makefile
+#     $(DEPEND):
+#             $(CC) -MM $(srcdir)/*.c > $(DEPEND)
+#
+#     @ifGNUmake@ ifeq ($(DEPEND),$(wildcard $(DEPEND)))
+#     @ifGNUmake@ include $(DEPEND)
+#     @ifGNUmake@ endif
+#
+#   Then configure.in would normally contain:
+#
+#     AX_CHECK_GNU_MAKE()
+#     AC_OUTPUT(Makefile)
+#
+#   Then perhaps to cause gnu make to override any other make, we could do
+#   something like this (note that GNU make always looks for GNUmakefile
+#   first):
+#
+#     if  ! test x$_cv_gnu_make_command = x ; then
+#             mv Makefile GNUmakefile
+#             echo .DEFAULT: > Makefile ;
+#             echo \  $_cv_gnu_make_command \$@ >> Makefile;
+#     fi
+#
+#   Then, if any (well almost any) other make is called, and GNU make also
+#   exists, then the other make wraps the GNU make.
+#
+# LICENSE
+#
+#   Copyright (c) 2008 John Darrington <j.darrington@elvis.murdoch.edu.au>
+#
+#   Copying and distribution of this file, with or without modification, are
+#   permitted in any medium without royalty provided the copyright notice
+#   and this notice are preserved. This file is offered as-is, without any
+#   warranty.
+
+#serial 7
+
+
+
 # Copyright (C) 2014 Jim Fougeron, for John Ripper project.
 # This file put into public domain. unlimited permission to
 # copy and/or distribute it, with or without modifications,
@@ -3402,54 +3463,6 @@ ac_config_headers="$ac_config_headers autoconfig.h"
 
 
 
-
-# Workaround for .gitignore refusing to ignore Makefile since it is
-# a managed file (the stub). The result of this is a *local* workaround.
-if test -d "../.git"; then :
-  # Extract the first word of "git", so it can be a program name with args.
-set dummy git; ac_word=$2
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-$as_echo_n "checking for $ac_word... " >&6; }
-if ${ac_cv_prog_HAVE_GIT+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  if test -n "$HAVE_GIT"; then
-  ac_cv_prog_HAVE_GIT="$HAVE_GIT" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_HAVE_GIT="yes"
-    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_prog_HAVE_GIT" && ac_cv_prog_HAVE_GIT="no"
-fi
-fi
-HAVE_GIT=$ac_cv_prog_HAVE_GIT
-if test -n "$HAVE_GIT"; then
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $HAVE_GIT" >&5
-$as_echo "$HAVE_GIT" >&6; }
-else
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-fi
-
-
-  if test "x$HAVE_GIT" = xyes; then :
-  git update-index --assume-unchanged Makefile
-
-fi
-
-fi
 
 # Define precious variables. They get included in --help and need no AC_SUBST
 
@@ -6190,6 +6203,32 @@ fi
 $as_echo "$ac_cv_path_SED" >&6; }
  SED="$ac_cv_path_SED"
   rm -f conftest.sed
+
+ { $as_echo "$as_me:${as_lineno-$LINENO}: checking for GNU make" >&5
+$as_echo_n "checking for GNU make... " >&6; }
+if ${_cv_gnu_make_command+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  _cv_gnu_make_command='' ;
+                for a in "$MAKE" make gmake gnumake ; do
+                        if test -z "$a" ; then continue ; fi ;
+                        if  ( sh -c "$a --version" 2> /dev/null | grep GNU  2>&1 > /dev/null ) ;  then
+                                _cv_gnu_make_command=$a ;
+                                break;
+                        fi
+                done ;
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $_cv_gnu_make_command" >&5
+$as_echo "$_cv_gnu_make_command" >&6; } ;
+        if test  "x$_cv_gnu_make_command" != "x"  ; then
+                ifGNUmake='' ;
+        else
+                ifGNUmake='#' ;
+                { $as_echo "$as_me:${as_lineno-$LINENO}: result: \"Not found\"" >&5
+$as_echo "\"Not found\"" >&6; };
+        fi
+
 
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether ${MAKE-make} sets \$(MAKE)" >&5
 $as_echo_n "checking whether ${MAKE-make} sets \$(MAKE)... " >&6; }
@@ -13440,9 +13479,16 @@ PLUGFORMATS_OBJS=`echo *_plug.c | sed "s/\.c/.o/g"`
 echo "configure: creating ./john_build_rule.h"
 echo "#define JOHN_BLD \"${host_os} ${CPU_BIT_STR}-bit${using_x32} ${CPU_STR}-autoconf\"" > john_build_rule.h
 
+# Use GNUmakefile if we have gmake
+if test x$_cv_gnu_make_command = x; then :
+  makefile=Makefile
+else
+  makefile=GNUmakefile
+fi
+
 HOST_OS="$host_os"
 
-ac_config_files="$ac_config_files GNUmakefile Makefile aes/Makefile aes/aesni/Makefile aes/openssl/Makefile escrypt/Makefile"
+ac_config_files="$ac_config_files ${makefile} aes/Makefile aes/aesni/Makefile aes/openssl/Makefile escrypt/Makefile"
 
 ac_config_commands="$ac_config_commands default"
 
@@ -14147,8 +14193,7 @@ do
   case $ac_config_target in
     "autoconfig.h") CONFIG_HEADERS="$CONFIG_HEADERS autoconfig.h" ;;
     "arch.h") CONFIG_LINKS="$CONFIG_LINKS arch.h:$ARCH_LINK" ;;
-    "GNUmakefile") CONFIG_FILES="$CONFIG_FILES GNUmakefile" ;;
-    "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+    "${makefile}") CONFIG_FILES="$CONFIG_FILES ${makefile}" ;;
     "aes/Makefile") CONFIG_FILES="$CONFIG_FILES aes/Makefile" ;;
     "aes/aesni/Makefile") CONFIG_FILES="$CONFIG_FILES aes/aesni/Makefile" ;;
     "aes/openssl/Makefile") CONFIG_FILES="$CONFIG_FILES aes/openssl/Makefile" ;;
@@ -14933,6 +14978,58 @@ if test "x$endian" = "big"; then
 else
    using_endian="LE"
 fi
+if test x$_cv_gnu_make_command = x; then
+   use_make=make
+else
+   use_make=$_cv_gnu_make_command
+   # Workaround for .gitignore refusing to ignore Makefile since it is
+   # a managed file (the stub). The result of this is a *local* workaround.
+   if test -d "../.git"; then :
+  # Extract the first word of "git", so it can be a program name with args.
+set dummy git; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_HAVE_GIT+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$HAVE_GIT"; then
+  ac_cv_prog_HAVE_GIT="$HAVE_GIT" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_HAVE_GIT="yes"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_HAVE_GIT" && ac_cv_prog_HAVE_GIT="no"
+fi
+fi
+HAVE_GIT=$ac_cv_prog_HAVE_GIT
+if test -n "$HAVE_GIT"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $HAVE_GIT" >&5
+$as_echo "$HAVE_GIT" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+     if test "x$HAVE_GIT" = xyes; then :
+  git update-index --assume-unchanged Makefile
+
+fi
+
+fi
+fi
 
 if test "x$osx_assembler_warn" = xyes; then :
   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: **************************************************" >&5
@@ -14974,5 +15071,5 @@ BZ2 (gpg2john extra decompression logic) .... ${using_bz2}
 
 Install missing libraries to get any needed features that were omitted.
 
-Configure finished.  Do 'make -s' to compile.
+Configure finished.  Do '${use_make} -s' to compile.
 EOF
